version: '3.7'

services:

  web:
    build: .
    image: web
    container_name: web
    ports:
      - 80:5000
    environment: 
      - REDIS_URL="redis://redis:6379/0"
 
    command: uvicorn app.main:app --host 0.0.0.0 --port 5000
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  worker:
    image: web
    environment: 
      - REDIS_URL=redis://redis:6379/0
    command: rq worker --url redis://redis:6379/0 --with-scheduler
    volumes:
      - .:/usr/src/app
    depends_on:
      - redis

  redis:
    image: redis:6

  dashboard:
    build: ./dashboard
    image: dashboard
    container_name: dashboard
    ports:
      - 9181:9181
    command: rq-dashboard -H redis
    depends_on:
      - redis